version: '2'
services:
  api:
    # tell docker-compose which Dockerfile it needs to build
    build: .
    # map the port of phoenix to the local dev port
    ports:
      - "4000:4000"
    # mount the code folder inside the running container for easy development
    volumes:
      - .:/app
    # make sure we start postgres when we start this service
    depends_on:
      - db
  db:
    # use postgres 9.3.17
    image: postgres:9.3.17-alpine
    # map the data volume, this is the way to keep our data persisitent
    volumes:
       - db_data:/var/lib/postgresql/data
    # set the user and password for postgres
    environment:
      - POSTGRES_DATABASE=api_banking
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
# create a named datavolume
volumes:
    db_data: